// GENERATED by scripts/sync-run-transfer-schema.mjs -- do not edit.
//
// Source of truth: plandev-examples/tools/run_transfer/run-transfer.v1.schema.json,
// which is where the format reference and the fixtures live too. Re-run the script after editing it
// there; `--check` fails if this file is stale.
//
// Draft-07, matching the ajv ^6 this repo pins. Authoring 2020-12 and discovering the mismatch at
// runtime is the failure that pin exists to prevent.
export const runTransferSchema = {
  "$id": "https://nasa-ammos.github.io/plandev-examples/run-transfer.v1.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "definitions": {
    "activity": {
      "properties": {
        "anchor_id": {
          "description": "Null for an offset from the plan start; otherwise the `localId` of another activity in this file.",
          "type": [
            "string",
            "null"
          ]
        },
        "anchored_to_start": {
          "type": "boolean"
        },
        "arguments": {
          "type": "object"
        },
        "id": {
          "description": "Permitted so a plain plan export round-trips, and ignored: `localId` is the keyspace."
        },
        "localId": {
          "description": "Unique within this file. Spans reference directives by it, and so do anchors: Postgres assigns real ids only on insert.",
          "minLength": 1,
          "type": "string"
        },
        "metadata": {
          "type": "object"
        },
        "name": {
          "type": "string"
        },
        "start_offset": {
          "$ref": "#/definitions/pgInterval"
        },
        "tags": {
          "items": {
            "properties": {
              "tag": {
                "properties": {
                  "color": {
                    "type": [
                      "string",
                      "null"
                    ]
                  },
                  "name": {
                    "minLength": 1,
                    "type": "string"
                  }
                },
                "required": [
                  "name"
                ],
                "type": "object"
              }
            },
            "required": [
              "tag"
            ],
            "type": "object"
          },
          "type": "array"
        },
        "type": {
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "localId",
        "type",
        "start_offset",
        "arguments"
      ],
      "type": "object"
    },
    "activityType": {
      "properties": {
        "computedAttributesSchema": {
          "$ref": "#/definitions/valueSchema",
          "description": "Not optional. A model that computes nothing declares a closed empty struct."
        },
        "description": {
          "type": "string"
        },
        "name": {
          "$ref": "#/definitions/tsIdentifier"
        },
        "parameters": {
          "description": "ORDER IS LOAD-BEARING: merlin persists each parameter's index as its `order` and the UI lays the argument form out in it.",
          "items": {
            "$ref": "#/definitions/modelParameter"
          },
          "type": "array"
        },
        "requiredParameters": {
          "items": {
            "type": "string"
          },
          "type": "array"
        },
        "subsystem": {
          "type": "string"
        }
      },
      "required": [
        "name",
        "parameters",
        "requiredParameters",
        "computedAttributesSchema"
      ],
      "type": "object"
    },
    "capability": {
      "if": {
        "properties": {
          "supported": {
            "const": false
          }
        },
        "required": [
          "supported"
        ]
      },
      "properties": {
        "reason": {
          "minLength": 1,
          "type": "string"
        },
        "supported": {
          "type": "boolean"
        }
      },
      "required": [
        "supported"
      ],
      "then": {
        "description": "An unsupported capability MUST carry its own sentence: that string is what the UI shows, and it is the only way the UI stays free of branches naming a producer.",
        "required": [
          "reason"
        ]
      },
      "type": "object"
    },
    "discreteSegment": {
      "properties": {
        "duration": {
          "type": "integer"
        },
        "dynamics": {
          "$ref": "#/definitions/serializedValue"
        }
      },
      "required": [
        "duration"
      ],
      "type": "object"
    },
    "model": {
      "description": "Omit to attach the run to an existing model by id, exactly as importPlan works today.",
      "properties": {
        "activityTypes": {
          "items": {
            "$ref": "#/definitions/activityType"
          },
          "type": "array"
        },
        "capabilities": {
          "additionalProperties": {
            "$ref": "#/definitions/capability"
          },
          "type": "object"
        },
        "description": {
          "type": "string"
        },
        "mission": {
          "minLength": 1,
          "type": "string"
        },
        "name": {
          "minLength": 1,
          "type": "string"
        },
        "parameters": {
          "description": "Simulation configuration. ORDER IS LOAD-BEARING, as for activity parameters.",
          "items": {
            "$ref": "#/definitions/modelParameter"
          },
          "type": "array"
        },
        "resourceTypes": {
          "items": {
            "$ref": "#/definitions/resourceType"
          },
          "type": "array"
        },
        "version": {
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "mission",
        "name",
        "version",
        "activityTypes",
        "resourceTypes",
        "parameters"
      ],
      "type": "object"
    },
    "modelParameter": {
      "properties": {
        "name": {
          "$ref": "#/definitions/tsIdentifier"
        },
        "schema": {
          "$ref": "#/definitions/valueSchema"
        }
      },
      "required": [
        "name",
        "schema"
      ],
      "type": "object"
    },
    "pgInterval": {
      "description": "A Postgres interval literal, as PlanTransfer v2 already uses: [-][N day[s] ]HH:MM:SS[.ffffff].",
      "pattern": "^-?(\\d+ days? )?\\d{2,}:[0-5]\\d:[0-5]\\d(\\.\\d{1,6})?$",
      "type": "string"
    },
    "plan": {
      "description": "A PlanTransfer v2 document, with two additions: every activity carries a `localId`, and `anchor_id` refers to one.",
      "properties": {
        "activities": {
          "items": {
            "$ref": "#/definitions/activity"
          },
          "type": "array"
        },
        "duration": {
          "$ref": "#/definitions/pgInterval"
        },
        "id": {},
        "model_id": {},
        "name": {
          "minLength": 1,
          "type": "string"
        },
        "simulation_arguments": {
          "type": "object"
        },
        "start_time": {
          "description": "ISO calendar date-time with a literal +00:00 suffix. A `Z` breaks the UI, which strips exactly that suffix. NOTE the asymmetry with results.startTime, which is day-of-year.",
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}(\\.\\d{1,6})?\\+00:00$",
          "type": "string"
        },
        "tags": {
          "items": {
            "properties": {
              "tag": {
                "properties": {
                  "color": {
                    "type": [
                      "string",
                      "null"
                    ]
                  },
                  "name": {
                    "minLength": 1,
                    "type": "string"
                  }
                },
                "required": [
                  "name"
                ],
                "type": "object"
              }
            },
            "required": [
              "tag"
            ],
            "type": "object"
          },
          "type": "array"
        },
        "version": {
          "const": "2",
          "description": "The PlanTransfer version, which is independent of the run transfer's own `version`."
        }
      },
      "required": [
        "version",
        "name",
        "start_time",
        "duration",
        "simulation_arguments",
        "activities"
      ],
      "type": "object"
    },
    "profile": {
      "allOf": [
        {
          "if": {
            "properties": {
              "type": {
                "const": "real"
              }
            },
            "required": [
              "type"
            ]
          },
          "then": {
            "properties": {
              "segments": {
                "items": {
                  "$ref": "#/definitions/realSegment"
                }
              }
            }
          }
        },
        {
          "if": {
            "properties": {
              "type": {
                "const": "discrete"
              }
            },
            "required": [
              "type"
            ]
          },
          "then": {
            "properties": {
              "segments": {
                "items": {
                  "$ref": "#/definitions/discreteSegment"
                }
              }
            }
          }
        }
      ],
      "properties": {
        "schema": {
          "$ref": "#/definitions/valueSchema"
        },
        "segments": {
          "description": "Consecutive from offset 0; each segment's duration is its extent, not a timestamp.",
          "type": "array"
        },
        "type": {
          "enum": [
            "real",
            "discrete"
          ]
        }
      },
      "required": [
        "type",
        "schema",
        "segments"
      ],
      "type": "object"
    },
    "realSegment": {
      "properties": {
        "duration": {
          "description": "Integer microseconds. Not constrained non-negative here on purpose: a negative duration is the gate's finding to make, not the schema's.",
          "type": "integer"
        },
        "dynamics": {
          "description": "Omit for a gap -- a legitimate 'this resource has no value here'. `rate` is per SECOND.",
          "properties": {
            "initial": {
              "type": "number"
            },
            "rate": {
              "type": "number"
            }
          },
          "required": [
            "initial",
            "rate"
          ],
          "type": "object"
        }
      },
      "required": [
        "duration"
      ],
      "type": "object"
    },
    "resourceName": {
      "description": "Always emitted quoted downstream, so spaces and dots are legal; arrayed resources flatten to dotted names. Length and control characters are the gate's call, not the schema's.",
      "minLength": 1,
      "type": "string"
    },
    "resourceType": {
      "properties": {
        "name": {
          "$ref": "#/definitions/resourceName"
        },
        "schema": {
          "$ref": "#/definitions/valueSchema"
        }
      },
      "required": [
        "name",
        "schema"
      ],
      "type": "object"
    },
    "results": {
      "description": "Byte-identical to what ingestExternalSimulationResults parses today, so v0 needs no new parsing code. Resource-major, and slated to be replaced by time-major NDJSON in version 2 -- see README.md.",
      "properties": {
        "duration": {
          "description": "Integer microseconds.",
          "minimum": 0,
          "type": "integer"
        },
        "profiles": {
          "additionalProperties": {
            "$ref": "#/definitions/profile"
          },
          "propertyNames": {
            "$ref": "#/definitions/resourceName"
          },
          "type": "object"
        },
        "spans": {
          "items": {
            "$ref": "#/definitions/span"
          },
          "type": "array"
        },
        "startTime": {
          "description": "DAY-OF-YEAR: uuuu-DDDTHH:MM:SS[.ffffff], which is what gov.nasa...types.Timestamp parses. A calendar date here is a parse failure.",
          "pattern": "^\\d{4}-\\d{3}T\\d{2}:[0-5]\\d:[0-5]\\d(\\.\\d{1,6})?$",
          "type": "string"
        }
      },
      "required": [
        "startTime",
        "duration",
        "profiles",
        "spans"
      ],
      "type": "object"
    },
    "serializedValue": {
      "description": "A SerializedValue: raw untagged JSON. Any JSON value, null included."
    },
    "span": {
      "properties": {
        "arguments": {
          "additionalProperties": {
            "$ref": "#/definitions/serializedValue"
          },
          "type": "object"
        },
        "computedAttributes": {
          "$ref": "#/definitions/serializedValue"
        },
        "directiveLocalId": {
          "description": "The `localId` of the directive this span belongs to. Omit for a span the model created itself.",
          "minLength": 1,
          "type": "string"
        },
        "duration": {
          "description": "Omit -- never null -- for a span still running when the simulation ended. That is stored as an unfinished activity.",
          "type": "integer"
        },
        "parentId": {
          "description": "A decomposition or dispatched child. Such a span carries no directiveLocalId. Omit for a root span; never send null.",
          "type": "integer"
        },
        "spanId": {
          "type": "integer"
        },
        "startOffset": {
          "description": "Integer microseconds from the simulation start.",
          "type": "integer"
        },
        "type": {
          "minLength": 1,
          "type": "string"
        }
      },
      "required": [
        "spanId",
        "type",
        "startOffset",
        "arguments"
      ],
      "type": "object"
    },
    "tsIdentifier": {
      "description": "An activity type or parameter name. It must survive as a bare TypeScript identifier in the generated typings, but that rule is NOT encoded here: ExternalResultsGate is its sole authority, and it owns the message that explains the consequence. See README.md, 'Two layers'.",
      "minLength": 1,
      "type": "string"
    },
    "valueSchema": {
      "allOf": [
        {
          "if": {
            "properties": {
              "type": {
                "const": "series"
              }
            },
            "required": [
              "type"
            ]
          },
          "then": {
            "properties": {
              "items": {
                "$ref": "#/definitions/valueSchema"
              }
            },
            "required": [
              "items"
            ]
          }
        },
        {
          "if": {
            "properties": {
              "type": {
                "const": "struct"
              }
            },
            "required": [
              "type"
            ]
          },
          "then": {
            "properties": {
              "items": {
                "additionalProperties": {
                  "$ref": "#/definitions/valueSchema"
                },
                "type": "object"
              }
            },
            "required": [
              "items"
            ]
          }
        },
        {
          "if": {
            "properties": {
              "type": {
                "const": "variant"
              }
            },
            "required": [
              "type"
            ]
          },
          "then": {
            "properties": {
              "variants": {
                "items": {
                  "properties": {
                    "key": {
                      "type": "string"
                    },
                    "label": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "key",
                    "label"
                  ],
                  "type": "object"
                },
                "type": "array"
              }
            },
            "required": [
              "variants"
            ]
          }
        }
      ],
      "description": "A ValueSchema, as ValueSchemaJsonParser reads it. Recursive and tagged on `type`.",
      "properties": {
        "metadata": {
          "additionalProperties": {
            "$ref": "#/definitions/serializedValue"
          },
          "type": "object"
        },
        "type": {
          "enum": [
            "real",
            "int",
            "boolean",
            "string",
            "duration",
            "path",
            "series",
            "struct",
            "variant"
          ]
        }
      },
      "required": [
        "type"
      ],
      "type": "object"
    }
  },
  "description": "A recorded simulation: model type declaration, plan directives, and results. Draft-07 deliberately, to match the ajv ^6 pinned in aerie-gateway. Normative prose: README.md, beside this schema",
  "properties": {
    "kind": {
      "const": "plandev-run",
      "description": "Refused outright if anything else. A file with no `kind` at all is a legacy plan.json and is not a run transfer."
    },
    "model": {
      "$ref": "#/definitions/model"
    },
    "plan": {
      "$ref": "#/definitions/plan"
    },
    "results": {
      "$ref": "#/definitions/results"
    },
    "version": {
      "const": "1",
      "description": "Major only. A reader refuses a version it does not know rather than best-effort parsing it."
    }
  },
  "required": [
    "kind",
    "version",
    "plan"
  ],
  "title": "PlanDev run transfer, version 1",
  "type": "object"
} as const;
